-- Tabella Categorie
CREATE TABLE categories (
    id bigint generated by default as identity primary key,
    name text not null,
    parent_id bigint references categories(id) on delete cascade,
    user_id uuid references auth.users(id) on delete cascade not null
);

-- Tabella Appunti
CREATE TABLE notes (
    id bigint generated by default as identity primary key,
    title text not null,
    content text,
    category_id bigint references categories(id) on delete cascade,
    user_id uuid references auth.users(id) on delete cascade not null
);

-- Abilitare Row Level Security (RLS) per sicurezza
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

-- Policy per categories
CREATE POLICY "Utenti vedono solo proprie categorie" ON categories
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Utenti inseriscono proprie categorie" ON categories
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Utenti modificano proprie categorie" ON categories
FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Utenti cancellano proprie categorie" ON categories
FOR DELETE USING (auth.uid() = user_id);

-- Policy per notes
CREATE POLICY "Utenti vedono propri appunti" ON notes
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Utenti inseriscono propri appunti" ON notes
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Utenti modificano propri appunti" ON notes
FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Utenti cancellano propri appunti" ON notes
FOR DELETE USING (auth.uid() = user_id);

-- Indici per migliorare le performance di ricerca
CREATE INDEX idx_notes_title ON notes (title);
CREATE INDEX idx_categories_parent ON categories (parent_id);
